<<<<<<< HEAD
# Generated by Django 3.1.1 on 2020-09-30 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 21, 11, 38, 772352, tzinfo=utc))),
                ('data', models.TextField()),
                ('locationOfData', models.CharField(max_length=100)),
                ('typeOfData', models.TextField()),
                ('argument', models.TextField()),
            ],
        ),
    ]
=======
# Generated by Django 3.1.1 on 2020-09-30 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 21, 11, 38, 772352, tzinfo=utc))),
                ('data', models.TextField()),
                ('locationOfData', models.CharField(max_length=100)),
                ('typeOfData', models.TextField()),
                ('argument', models.TextField()),
            ],
        ),
    ]
>>>>>>> bb806d06e1365e7e16a45a26f04abc01c041c109
